#pragma once
#include <linc/bound_tree/BoundNode.hpp>
#include <linc/bound_tree/BoundExpression.hpp>
#include <linc/bound_tree/BoundLiteralExpression.hpp>
#include <linc/bound_tree/BoundIdentifierExpression.hpp>
#include <linc/bound_tree/BoundIfElseExpression.hpp>
#include <linc/bound_tree/BoundWhileExpression.hpp>
#include <linc/bound_tree/BoundUnaryExpression.hpp>
#include <linc/bound_tree/BoundBinaryExpression.hpp>
#include <linc/bound_tree/BoundStatement.hpp>
#include <linc/bound_tree/BoundExpressionStatement.hpp>
#include <linc/bound_tree/BoundScopeStatement.hpp>
#include <linc/bound_tree/BoundVariableDeclarationStatement.hpp>
#include <linc/bound_tree/BoundPutCharacterStatement.hpp>
#include <linc/bound_tree/BoundPutStringStatement.hpp>