#pragma once
#include <cstdio>
#include <cstdint>
#include <stdfloat>
#include <string>
#include <string_view>
#include <optional>
#include <variant>
#include <vector>
#include <array>
#include <stack>
#include <deque>
#include <unordered_map>
#include <unordered_set>
#include <fstream>
#include <sstream>
#include <iostream>
#include <filesystem>
#include <utility>
#include <memory>